### ISSUE TITLE
Add to FreeCAD Addon Manager 

### ISSUE THREAD

**Issue by luzpaz** [heissgetraenk/fcmcua#17]
https://github.com/FreeCAD/FreeCAD-addons#adding-your-workbench-to-the-collection

**Comment by luzpaz** [comment]
What are the 3rd party dependencies of this workbench?

**Comment by heissgetraenk** [comment]
asyncua, which in turn needs aiofiles

**Comment by luzpaz** [comment]
Thanks, are they available via `pip` ? If so what are their official names?

**Comment by heissgetraenk** [comment]
pip install asyncua installs both, i believe. 
https://github.com/FreeOpcUa/opcua-asyncio

**Comment by luzpaz** [comment]
@chennes will the addon manager autoinstall both if one is the dependency of the other? :point_up_2:

**Comment by chennes** [comment]
Yes, the AM just uses pip, so it will follow whatever dependency chain a normal pip install does. You only need to specify your actual dependency, not all the things it depends on.

**Comment by luzpaz** [comment]
Are we good to add  'asyncua' (https://github.com/FreeOpcUa/opcua-asyncio) to the https://github.com/FreeCAD/FreeCAD-addons/blob/master/ALLOWED_PYTHON_PACKAGES.txt file ?

**Comment by chennes** [comment]
No problems here.

**Comment by luzpaz** [comment]
Thanks chennes. Merged in https://github.com/FreeCAD/FreeCAD-addons/pull/248  
Now we need a `package.xml`
