### ISSUE TITLE
Check encoding of package.xml

### ISSUE THREAD

**Issue by chennes** [heissgetraenk/fcmcua#27]
The package.xml file currently in place is either not UTF-8 encoded, or it is but includes a header bit (which is not permitted in a package.xml file).

**Comment by heissgetraenk** [comment]
I found some weird invisible chars in the header line after standalone="no". Namely a #xC2 and a #x0A which I feel like don't belong in there. Removing them hopefully fixes it. 

From what I can tell, those chars seem to come from copy and pasting the example xml from https://wiki.freecad.org/Package_Metadata#Examples ...

![xml_parse_error](https://user-images.githubusercontent.com/104628764/213137741-a18ab6da-f782-4285-9599-488309335f8f.png)
