### ISSUE TITLE
FreeCad addon manager: installing dependency

### ISSUE THREAD

**Issue by heissgetraenk** [heissgetraenk/fcmcua#30]
@chennes where does the addon manager install dependencies to? 
Or rather: Is adding <depend>asyncua</depend> to the package.xml enough to get it installed or am I missing something?

**Comment by chennes** [comment]
Two part answer: you shouldn't have to care about that, just specify the dependency in package.xml and FreeCAD will find it where the AM puts it. It's putting it in FREECAD_USER_DIR/AdditionalPythonPackages.

**Comment by heissgetraenk** [comment]
I worked this time around. For some reason it didn't prompt me to install the depedency earlier. It did now and installed perfectly. Thanks again!
